<?php
if (!defined('ABSPATH')) {
    exit;
}

class KSSCTB_Settings {
    private static $instance = null;
    private $option_name = 'kssctb_settings';
    private $settings_cache = null;

    public static function get_instance() {
        if (null === self::$instance) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    private function __construct() {
    }

    public function get_all_settings() {
        if (null === $this->settings_cache) {
            $this->settings_cache = get_option($this->option_name, $this->get_default_settings());
        }
        return $this->settings_cache;
    }

    public function get_settings($content_type) {
        $settings = $this->get_all_settings();
        return isset($settings[$content_type]) ? $settings[$content_type] : array();
    }

    public function update_settings($settings) {
        $result = update_option($this->option_name, $settings);
        // キャッシュをクリア
        $this->settings_cache = $settings;

        // update_optionは値が同じ場合falseを返すが、これは成功とみなす
        // オプションが存在するかチェックして、存在すれば成功
        return $result || get_option($this->option_name) !== false;
    }

    public function create_default_settings() {
        if (!get_option($this->option_name)) {
            add_option($this->option_name, $this->get_default_settings());
        }
    }

    /**
     * ユーザー個別のSchema情報を取得
     *
     * @param int $user_id ユーザーID
     * @return array ユーザーのSchema情報
     */
    public function get_user_schema_data($user_id) {
        if (!$user_id) {
            return $this->get_default_user_schema_data();
        }

        $user_data = array(
            'job_title' => get_user_meta($user_id, 'kssctb_job_title', true),
            'works_for' => get_user_meta($user_id, 'kssctb_works_for', true),
            'description' => get_user_meta($user_id, 'kssctb_description', true),
            'address' => get_user_meta($user_id, 'kssctb_address', true),
            'telephone' => get_user_meta($user_id, 'kssctb_telephone', true),
            'knows_about' => get_user_meta($user_id, 'kssctb_knows_about', true),
            'alumni_of' => get_user_meta($user_id, 'kssctb_alumni_of', true),
            'profile_image' => get_user_meta($user_id, 'kssctb_profile_image', true),
            'profile_url' => get_user_meta($user_id, 'kssctb_profile_url', true)
        );

        // 空の値にはデフォルト値を設定
        return array_merge($this->get_default_user_schema_data(), array_filter($user_data));
    }

    /**
     * ユーザー個別のSchema情報を保存
     *
     * @param int $user_id ユーザーID
     * @param array $data 保存するデータ
     * @return bool 保存結果
     */
    public function update_user_schema_data($user_id, $data) {
        if (!$user_id) {
            return false;
        }

        $fields = array(
            'job_title', 'works_for', 'description', 'address',
            'telephone', 'knows_about', 'alumni_of', 'profile_image', 'profile_url'
        );

        foreach ($fields as $field) {
            if (isset($data[$field])) {
                update_user_meta($user_id, 'kssctb_' . $field, sanitize_text_field($data[$field]));
            }
        }

        return true;
    }

    /**
     * ユーザーSchema情報のデフォルト値を取得
     *
     * @return array デフォルト値の配列
     */
    private function get_default_user_schema_data() {
        return array(
            'job_title' => '',
            'works_for' => '',
            'description' => '',
            'address' => '',
            'telephone' => '',
            'knows_about' => '',
            'alumni_of' => '',
            'profile_image' => '',
            'profile_url' => ''
        );
    }

    private function get_default_settings() {
        return array(
            'general' => array(
                'enable_debug_log' => false,
                'enable_breadcrumb' => false
            ),
            'article' => array(
                'enabled' => false,
                'post_types' => array(),
                'archive_types' => array(),
                'publisher_type' => 'none',
                'publisher_person_user' => '',
                'publisher_person_url' => '',
                'publisher_person_image' => '',
                'publisher_person_job_title' => '',
                'publisher_person_works_for' => '',
                'publisher_person_description' => '',
                'publisher_person_address' => '',
                'publisher_person_telephone' => '',
                'publisher_person_knows_about' => '',
                'publisher_person_alumni_of' => '',
                'publisher_organization_name' => '',
                'publisher_organization_url' => '',
                'publisher_organization_logo' => '',
                'publisher_organization_street_address' => '',
                'publisher_organization_address_locality' => '',
                'publisher_organization_address_region' => '',
                'publisher_organization_postal_code' => '',
                'publisher_organization_address_country' => '',
                'publisher_organization_telephone' => '',
                'publisher_organization_description' => '',
                'publisher_organization_legal_name' => '',
                'publisher_organization_founding_date' => '',
                'publisher_organization_number_of_employees' => '',
                'publisher_organization_same_as' => '',
                'publisher_corporation_name' => '',
                'publisher_corporation_url' => '',
                'publisher_corporation_logo' => '',
                'publisher_corporation_address' => '',
                'publisher_corporation_street_address' => '',
                'publisher_corporation_address_locality' => '',
                'publisher_corporation_address_region' => '',
                'publisher_corporation_postal_code' => '',
                'publisher_corporation_address_country' => '',
                'publisher_corporation_telephone' => '',
                'publisher_corporation_description' => '',
                'publisher_corporation_representative_name' => '',
                'publisher_corporation_representative_title' => '',
                'publisher_corporation_founding_date' => '',
                'publisher_corporation_corporate_number' => '',
                'publisher_corporation_social_media' => '',
                'default_author_type' => 'none',
                'author_person_user' => '',
                'author_person_url' => '',
                'author_person_image' => '',
                'author_person_job_title' => '',
                'author_person_works_for' => '',
                'author_person_description' => '',
                'author_person_address' => '',
                'author_person_telephone' => '',
                'author_person_knows_about' => '',
                'author_person_alumni_of' => '',
                'author_organization_name' => '',
                'author_organization_url' => '',
                'author_organization_logo' => '',
                'author_organization_street_address' => '',
                'author_organization_address_locality' => '',
                'author_organization_address_region' => '',
                'author_organization_postal_code' => '',
                'author_organization_address_country' => '',
                'author_organization_telephone' => '',
                'author_organization_description' => '',
                'author_organization_legal_name' => '',
                'author_organization_founding_date' => '',
                'author_organization_number_of_employees' => '',
                'author_organization_same_as' => '',
                'author_corporation_name' => '',
                'author_corporation_url' => '',
                'author_corporation_logo' => '',
                'author_corporation_address' => '',
                'author_corporation_street_address' => '',
                'author_corporation_address_locality' => '',
                'author_corporation_address_region' => '',
                'author_corporation_postal_code' => '',
                'author_corporation_address_country' => '',
                'author_corporation_telephone' => '',
                'author_corporation_description' => '',
                'author_corporation_representative_name' => '',
                'author_corporation_representative_title' => '',
                'author_corporation_founding_date' => '',
                'author_corporation_corporate_number' => '',
                'author_corporation_social_media' => '',
                'sponsor_type' => 'none',
                'sponsor_person_user' => '',
                'sponsor_person_url' => '',
                'sponsor_person_image' => '',
                'sponsor_person_job_title' => '',
                'sponsor_person_works_for' => '',
                'sponsor_person_description' => '',
                'sponsor_person_address' => '',
                'sponsor_person_telephone' => '',
                'sponsor_person_knows_about' => '',
                'sponsor_person_alumni_of' => '',
                'sponsor_organization_name' => '',
                'sponsor_organization_url' => '',
                'sponsor_organization_logo' => '',
                'sponsor_organization_street_address' => '',
                'sponsor_organization_address_locality' => '',
                'sponsor_organization_address_region' => '',
                'sponsor_organization_postal_code' => '',
                'sponsor_organization_address_country' => '',
                'sponsor_organization_telephone' => '',
                'sponsor_organization_description' => '',
                'sponsor_organization_legal_name' => '',
                'sponsor_organization_founding_date' => '',
                'sponsor_organization_number_of_employees' => '',
                'sponsor_organization_same_as' => '',
                'sponsor_corporation_name' => '',
                'sponsor_corporation_url' => '',
                'sponsor_corporation_logo' => '',
                'sponsor_corporation_address' => '',
                'sponsor_corporation_street_address' => '',
                'sponsor_corporation_address_locality' => '',
                'sponsor_corporation_address_region' => '',
                'sponsor_corporation_postal_code' => '',
                'sponsor_corporation_address_country' => '',
                'sponsor_corporation_telephone' => '',
                'sponsor_corporation_description' => '',
                'sponsor_corporation_representative_name' => '',
                'sponsor_corporation_representative_title' => '',
                'sponsor_corporation_founding_date' => '',
                'sponsor_corporation_corporate_number' => '',
                'sponsor_corporation_social_media' => '',
                'article_section' => ''
            ),
            'newsarticle' => array(
                'enabled' => false,
                'post_types' => array(),
                'archive_types' => array(),
                'publisher_type' => 'none',
                'publisher_person_user' => '',
                'publisher_person_url' => '',
                'publisher_person_image' => '',
                'publisher_person_job_title' => '',
                'publisher_person_works_for' => '',
                'publisher_person_description' => '',
                'publisher_person_address' => '',
                'publisher_person_telephone' => '',
                'publisher_person_knows_about' => '',
                'publisher_person_alumni_of' => '',
                'publisher_organization_name' => '',
                'publisher_organization_url' => '',
                'publisher_organization_logo' => '',
                'publisher_organization_street_address' => '',
                'publisher_organization_address_locality' => '',
                'publisher_organization_address_region' => '',
                'publisher_organization_postal_code' => '',
                'publisher_organization_address_country' => '',
                'publisher_organization_telephone' => '',
                'publisher_organization_description' => '',
                'publisher_organization_legal_name' => '',
                'publisher_organization_founding_date' => '',
                'publisher_organization_number_of_employees' => '',
                'publisher_organization_same_as' => '',
                'publisher_corporation_name' => '',
                'publisher_corporation_url' => '',
                'publisher_corporation_logo' => '',
                'publisher_corporation_address' => '',
                'publisher_corporation_street_address' => '',
                'publisher_corporation_address_locality' => '',
                'publisher_corporation_address_region' => '',
                'publisher_corporation_postal_code' => '',
                'publisher_corporation_address_country' => '',
                'publisher_corporation_telephone' => '',
                'publisher_corporation_description' => '',
                'publisher_corporation_representative_name' => '',
                'publisher_corporation_representative_title' => '',
                'publisher_corporation_founding_date' => '',
                'publisher_corporation_corporate_number' => '',
                'publisher_corporation_social_media' => '',
                'default_author_type' => 'none',
                'author_person_user' => '',
                'author_person_url' => '',
                'author_person_image' => '',
                'author_person_job_title' => '',
                'author_person_works_for' => '',
                'author_person_description' => '',
                'author_person_address' => '',
                'author_person_telephone' => '',
                'author_person_knows_about' => '',
                'author_person_alumni_of' => '',
                'author_organization_name' => '',
                'author_organization_url' => '',
                'author_organization_logo' => '',
                'author_organization_street_address' => '',
                'author_organization_address_locality' => '',
                'author_organization_address_region' => '',
                'author_organization_postal_code' => '',
                'author_organization_address_country' => '',
                'author_organization_telephone' => '',
                'author_organization_description' => '',
                'author_organization_legal_name' => '',
                'author_organization_founding_date' => '',
                'author_organization_number_of_employees' => '',
                'author_organization_same_as' => '',
                'author_corporation_name' => '',
                'author_corporation_url' => '',
                'author_corporation_logo' => '',
                'author_corporation_address' => '',
                'author_corporation_street_address' => '',
                'author_corporation_address_locality' => '',
                'author_corporation_address_region' => '',
                'author_corporation_postal_code' => '',
                'author_corporation_address_country' => '',
                'author_corporation_telephone' => '',
                'author_corporation_description' => '',
                'author_corporation_representative_name' => '',
                'author_corporation_representative_title' => '',
                'author_corporation_founding_date' => '',
                'author_corporation_corporate_number' => '',
                'author_corporation_social_media' => '',
                'sponsor_type' => 'none',
                'sponsor_person_user' => '',
                'sponsor_person_url' => '',
                'sponsor_person_image' => '',
                'sponsor_person_job_title' => '',
                'sponsor_person_works_for' => '',
                'sponsor_person_description' => '',
                'sponsor_person_address' => '',
                'sponsor_person_telephone' => '',
                'sponsor_person_knows_about' => '',
                'sponsor_person_alumni_of' => '',
                'sponsor_organization_name' => '',
                'sponsor_organization_url' => '',
                'sponsor_organization_logo' => '',
                'sponsor_organization_street_address' => '',
                'sponsor_organization_address_locality' => '',
                'sponsor_organization_address_region' => '',
                'sponsor_organization_postal_code' => '',
                'sponsor_organization_address_country' => '',
                'sponsor_organization_telephone' => '',
                'sponsor_organization_description' => '',
                'sponsor_organization_legal_name' => '',
                'sponsor_organization_founding_date' => '',
                'sponsor_organization_number_of_employees' => '',
                'sponsor_organization_same_as' => '',
                'sponsor_corporation_name' => '',
                'sponsor_corporation_url' => '',
                'sponsor_corporation_logo' => '',
                'sponsor_corporation_address' => '',
                'sponsor_corporation_street_address' => '',
                'sponsor_corporation_address_locality' => '',
                'sponsor_corporation_address_region' => '',
                'sponsor_corporation_postal_code' => '',
                'sponsor_corporation_address_country' => '',
                'sponsor_corporation_telephone' => '',
                'sponsor_corporation_description' => '',
                'sponsor_corporation_representative_name' => '',
                'sponsor_corporation_representative_title' => '',
                'sponsor_corporation_founding_date' => '',
                'sponsor_corporation_corporate_number' => '',
                'sponsor_corporation_social_media' => '',
                'news_keywords' => ''
            ),
            'blogposting' => array(
                'enabled' => false,
                'post_types' => array(),
                'archive_types' => array(),
                'publisher_type' => 'none',
                'publisher_person_user' => '',
                'publisher_person_url' => '',
                'publisher_person_image' => '',
                'publisher_person_job_title' => '',
                'publisher_person_works_for' => '',
                'publisher_person_description' => '',
                'publisher_person_address' => '',
                'publisher_person_telephone' => '',
                'publisher_person_knows_about' => '',
                'publisher_person_alumni_of' => '',
                'publisher_organization_name' => '',
                'publisher_organization_url' => '',
                'publisher_organization_logo' => '',
                'publisher_organization_street_address' => '',
                'publisher_organization_address_locality' => '',
                'publisher_organization_address_region' => '',
                'publisher_organization_postal_code' => '',
                'publisher_organization_address_country' => '',
                'publisher_organization_telephone' => '',
                'publisher_organization_description' => '',
                'publisher_organization_legal_name' => '',
                'publisher_organization_founding_date' => '',
                'publisher_organization_number_of_employees' => '',
                'publisher_organization_same_as' => '',
                'publisher_corporation_name' => '',
                'publisher_corporation_url' => '',
                'publisher_corporation_logo' => '',
                'publisher_corporation_address' => '',
                'publisher_corporation_street_address' => '',
                'publisher_corporation_address_locality' => '',
                'publisher_corporation_address_region' => '',
                'publisher_corporation_postal_code' => '',
                'publisher_corporation_address_country' => '',
                'publisher_corporation_telephone' => '',
                'publisher_corporation_description' => '',
                'publisher_corporation_representative_name' => '',
                'publisher_corporation_representative_title' => '',
                'publisher_corporation_founding_date' => '',
                'publisher_corporation_corporate_number' => '',
                'publisher_corporation_social_media' => '',
                'default_author_type' => 'none',
                'author_person_user' => '',
                'author_person_url' => '',
                'author_person_image' => '',
                'author_person_job_title' => '',
                'author_person_works_for' => '',
                'author_person_description' => '',
                'author_person_address' => '',
                'author_person_telephone' => '',
                'author_person_knows_about' => '',
                'author_person_alumni_of' => '',
                'author_organization_name' => '',
                'author_organization_url' => '',
                'author_organization_logo' => '',
                'author_organization_street_address' => '',
                'author_organization_address_locality' => '',
                'author_organization_address_region' => '',
                'author_organization_postal_code' => '',
                'author_organization_address_country' => '',
                'author_organization_telephone' => '',
                'author_organization_description' => '',
                'author_organization_legal_name' => '',
                'author_organization_founding_date' => '',
                'author_organization_number_of_employees' => '',
                'author_organization_same_as' => '',
                'author_corporation_name' => '',
                'author_corporation_url' => '',
                'author_corporation_logo' => '',
                'author_corporation_address' => '',
                'author_corporation_street_address' => '',
                'author_corporation_address_locality' => '',
                'author_corporation_address_region' => '',
                'author_corporation_postal_code' => '',
                'author_corporation_address_country' => '',
                'author_corporation_telephone' => '',
                'author_corporation_description' => '',
                'author_corporation_representative_name' => '',
                'author_corporation_representative_title' => '',
                'author_corporation_founding_date' => '',
                'author_corporation_corporate_number' => '',
                'author_corporation_social_media' => '',
                'sponsor_type' => 'none',
                'sponsor_person_user' => '',
                'sponsor_person_url' => '',
                'sponsor_person_image' => '',
                'sponsor_person_job_title' => '',
                'sponsor_person_works_for' => '',
                'sponsor_person_description' => '',
                'sponsor_person_address' => '',
                'sponsor_person_telephone' => '',
                'sponsor_person_knows_about' => '',
                'sponsor_person_alumni_of' => '',
                'sponsor_organization_name' => '',
                'sponsor_organization_url' => '',
                'sponsor_organization_logo' => '',
                'sponsor_organization_street_address' => '',
                'sponsor_organization_address_locality' => '',
                'sponsor_organization_address_region' => '',
                'sponsor_organization_postal_code' => '',
                'sponsor_organization_address_country' => '',
                'sponsor_organization_telephone' => '',
                'sponsor_organization_description' => '',
                'sponsor_organization_legal_name' => '',
                'sponsor_organization_founding_date' => '',
                'sponsor_organization_number_of_employees' => '',
                'sponsor_organization_same_as' => '',
                'sponsor_corporation_name' => '',
                'sponsor_corporation_url' => '',
                'sponsor_corporation_logo' => '',
                'sponsor_corporation_address' => '',
                'sponsor_corporation_street_address' => '',
                'sponsor_corporation_address_locality' => '',
                'sponsor_corporation_address_region' => '',
                'sponsor_corporation_postal_code' => '',
                'sponsor_corporation_address_country' => '',
                'sponsor_corporation_telephone' => '',
                'sponsor_corporation_description' => '',
                'sponsor_corporation_representative_name' => '',
                'sponsor_corporation_representative_title' => '',
                'sponsor_corporation_founding_date' => '',
                'sponsor_corporation_corporate_number' => '',
                'sponsor_corporation_social_media' => '',
                'enable_comments' => false
            ),
            'webpage' => array(
                'enabled' => false,
                'post_types' => array(),
                'archive_types' => array(),
                'publisher_type' => 'none',
                'publisher_person_user' => '',
                'publisher_person_url' => '',
                'publisher_person_image' => '',
                'publisher_person_job_title' => '',
                'publisher_person_works_for' => '',
                'publisher_person_description' => '',
                'publisher_person_address' => '',
                'publisher_person_telephone' => '',
                'publisher_person_knows_about' => '',
                'publisher_person_alumni_of' => '',
                'publisher_organization_name' => '',
                'publisher_organization_url' => '',
                'publisher_organization_logo' => '',
                'publisher_organization_street_address' => '',
                'publisher_organization_address_locality' => '',
                'publisher_organization_address_region' => '',
                'publisher_organization_postal_code' => '',
                'publisher_organization_address_country' => '',
                'publisher_organization_telephone' => '',
                'publisher_organization_description' => '',
                'publisher_organization_legal_name' => '',
                'publisher_organization_founding_date' => '',
                'publisher_organization_number_of_employees' => '',
                'publisher_organization_same_as' => '',
                'publisher_corporation_name' => '',
                'publisher_corporation_url' => '',
                'publisher_corporation_logo' => '',
                'publisher_corporation_address' => '',
                'publisher_corporation_street_address' => '',
                'publisher_corporation_address_locality' => '',
                'publisher_corporation_address_region' => '',
                'publisher_corporation_postal_code' => '',
                'publisher_corporation_address_country' => '',
                'publisher_corporation_telephone' => '',
                'publisher_corporation_description' => '',
                'publisher_corporation_representative_name' => '',
                'publisher_corporation_representative_title' => '',
                'publisher_corporation_founding_date' => '',
                'publisher_corporation_corporate_number' => '',
                'publisher_corporation_social_media' => '',
                'default_author_type' => 'none',
                'author_person_user' => '',
                'author_person_url' => '',
                'author_person_image' => '',
                'author_person_job_title' => '',
                'author_person_works_for' => '',
                'author_person_description' => '',
                'author_person_address' => '',
                'author_person_telephone' => '',
                'author_person_knows_about' => '',
                'author_person_alumni_of' => '',
                'author_organization_name' => '',
                'author_organization_url' => '',
                'author_organization_logo' => '',
                'author_organization_street_address' => '',
                'author_organization_address_locality' => '',
                'author_organization_address_region' => '',
                'author_organization_postal_code' => '',
                'author_organization_address_country' => '',
                'author_organization_telephone' => '',
                'author_organization_description' => '',
                'author_organization_legal_name' => '',
                'author_organization_founding_date' => '',
                'author_organization_number_of_employees' => '',
                'author_organization_same_as' => '',
                'author_corporation_name' => '',
                'author_corporation_url' => '',
                'author_corporation_logo' => '',
                'author_corporation_address' => '',
                'author_corporation_street_address' => '',
                'author_corporation_address_locality' => '',
                'author_corporation_address_region' => '',
                'author_corporation_postal_code' => '',
                'author_corporation_address_country' => '',
                'author_corporation_telephone' => '',
                'author_corporation_description' => '',
                'author_corporation_representative_name' => '',
                'author_corporation_representative_title' => '',
                'author_corporation_founding_date' => '',
                'author_corporation_corporate_number' => '',
                'author_corporation_social_media' => '',
                'sponsor_type' => 'none',
                'sponsor_person_user' => '',
                'sponsor_person_url' => '',
                'sponsor_person_image' => '',
                'sponsor_person_job_title' => '',
                'sponsor_person_works_for' => '',
                'sponsor_person_description' => '',
                'sponsor_person_address' => '',
                'sponsor_person_telephone' => '',
                'sponsor_person_knows_about' => '',
                'sponsor_person_alumni_of' => '',
                'sponsor_organization_name' => '',
                'sponsor_organization_url' => '',
                'sponsor_organization_logo' => '',
                'sponsor_organization_street_address' => '',
                'sponsor_organization_address_locality' => '',
                'sponsor_organization_address_region' => '',
                'sponsor_organization_postal_code' => '',
                'sponsor_organization_address_country' => '',
                'sponsor_organization_telephone' => '',
                'sponsor_organization_description' => '',
                'sponsor_organization_legal_name' => '',
                'sponsor_organization_founding_date' => '',
                'sponsor_organization_number_of_employees' => '',
                'sponsor_organization_same_as' => '',
                'sponsor_corporation_name' => '',
                'sponsor_corporation_url' => '',
                'sponsor_corporation_logo' => '',
                'sponsor_corporation_address' => '',
                'sponsor_corporation_street_address' => '',
                'sponsor_corporation_address_locality' => '',
                'sponsor_corporation_address_region' => '',
                'sponsor_corporation_postal_code' => '',
                'sponsor_corporation_address_country' => '',
                'sponsor_corporation_telephone' => '',
                'sponsor_corporation_description' => '',
                'sponsor_corporation_representative_name' => '',
                'sponsor_corporation_representative_title' => '',
                'sponsor_corporation_founding_date' => '',
                'sponsor_corporation_corporate_number' => '',
                'sponsor_corporation_social_media' => '',
                'enable_speakable' => false
            )
        );
    }
}
